services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: time
      POSTGRES_PASSWORD: attack
      POSTGRES_DB: zeroWaste
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
